In [4]:
import pandas as pd
import numpy as np
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler, Stream, API, Cursor, OAuthHandler
import tweetercred

In [2]:
import requests
import pymongo
import datetime as dt

In [53]:
!GetOldTweets3 --username "lopezobrador_" --since 2016-12-01 --until 2020-02-24

/bin/sh: GetOldTweets3: command not found

In [104]:
#creates connection to mongodb database table
client = pymongo.MongoClient()
db = client.tweeter
collections = db.trump_tweets

In [28]:
from twitterscraper import query_tweets, query_tweets_from_user,

In [20]:
begin_date = dt.date(2020,2,1)
end_date = dt.date(2020,2,23)
lang = 'english'

In [47]:
user = 'lopezobrador_'

In [61]:
# amlotweets = query_tweets_from_user(user=user, limit=5000)

In [62]:
# tweets = query_tweets(user, begindate=begin_date, enddate=end_date, lang=lang)

In [49]:
amlo_df = pd.DataFrame(t.__dict__ for t in amlotweets)

In [30]:
t_df = pd.DataFrame(t.__dict__ for t in trumptweets)

In [50]:
amlo_df.tail()

,screen_name,username,user_id,tweet_id,tweet_url,timestamp,timestamp_epochs,text,text_html,links,...,has_media,img_urls,video_url,likes,retweets,replies,is_replied,is_reply_to,parent_tweet_id,reply_to_users
609,lopezobrador_,Andrés Manuel,82119937,1076276251919245313,/lopezobrador_/status/1076276251919245313,2018-12-22 00:40:29,1545439229,Hoy dimos a conocer en Oaxaca el Programa Naci...,"<p class=""TweetTextSize TweetTextSize--normal ...",[https://youtu.be/emXvigI8MZ8],...,True,[https://pbs.twimg.com/media/Du-ziwIU8AAXl9W.jpg],,7117,1770,547,True,False,,[]
610,lopezobrador_,Andrés Manuel,82119937,1076103200048992257,/lopezobrador_/status/1076103200048992257,2018-12-21 13:12:50,1545397970,"Previo a gira por Oaxaca, conversamos con los ...","<p class=""TweetTextSize TweetTextSize--normal ...",[https://www.pscp.tv/w/buzeUjF4TlFhYWVySmVhUWJ...,...,False,[],,4872,1311,550,True,False,,[]
611,lopezobrador_,Andrés Manuel,82119937,1075740113102036994,/lopezobrador_/status/1075740113102036994,2018-12-20 13:10:03,1545311403,"Como cada mañana, respondemos las preguntas de...","<p class=""TweetTextSize TweetTextSize--normal ...",[https://www.pscp.tv/w/buuMKzF4TlFhYWVySmVhUWJ...,...,False,[],,7042,1756,881,True,False,,[]
612,lopezobrador_,Andrés Manuel,82119937,1075560792815218688,/lopezobrador_/status/1075560792815218688,2018-12-20 01:17:30,1545268650,Carlos Payán es un fiel heredero del periodism...,"<p class=""TweetTextSize TweetTextSize--normal ...",[],...,True,[https://pbs.twimg.com/media/Du0o1liUwAAslSv.jpg],,7131,1705,238,True,False,,[]
613,lopezobrador_,Andrés Manuel,82119937,1075503290828259328,/lopezobrador_/status/1075503290828259328,2018-12-19 21:29:01,1545254941,"Conversamos con directivos de Hydro-Québec, un...","<p class=""TweetTextSize TweetTextSize--normal ...",[https://youtu.be/39RlJAjPLfI],...,True,[https://pbs.twimg.com/media/Duz0hqzUYAA6Yme.jpg],,13677,4178,1025,True,False,,[]

In [32]:
t_df.head()

,screen_name,username,user_id,tweet_id,tweet_url,timestamp,timestamp_epochs,text,text_html,links,...,has_media,img_urls,video_url,likes,retweets,replies,is_replied,is_reply_to,parent_tweet_id,reply_to_users
0,dcexaminer,Washington Examiner,18956073,1231615748382117889,/dcexaminer/status/1231615748382117889,2020-02-23 16:24:11,1582475051,'Party of jobs': Ted Cruz predicts blue-collar...,"<p class=""TweetTextSize TweetTextSize--normal ...",[https://washex.am/2PiRIUk],...,False,[],,2058,571,116,True,False,,[]
1,GOP,GOP,11134252,1231730481038790656,/GOP/status/1231730481038790656,2020-02-24 00:00:05,1582502405,President @realDonaldTrump’s Administration is...,"<p class=""TweetTextSize TweetTextSize--normal ...",[https://www.wsj.com/articles/trump-takes-a-st...,...,False,[],,7561,2502,1183,True,False,,[]
2,GOP,GOP,11134252,1231938080086667264,/GOP/status/1231938080086667264,2020-02-24 13:45:01,1582551901,"At a packed rally in Las Vegas on Friday, Pres...","<p class=""TweetTextSize TweetTextSize--normal ...",[https://twitter.com/parscale/status/123098358...,...,False,[],,4280,1284,206,True,False,,[]
3,KatrinaCampins,KATRINA CAMPINS,34852681,1231691372996038657,/KatrinaCampins/status/1231691372996038657,2020-02-23 21:24:41,1582493081,HUGE Latino support in Miami today for @realDo...,"<p class=""TweetTextSize TweetTextSize--normal ...",[],...,True,[https://pbs.twimg.com/media/ERfYxiGXsAAjjCY.jpg],,5105,1587,201,True,False,,[]
4,PressSec,Stephanie Grisham,818927131883356161,1231860696490692609,/PressSec/status/1231860696490692609,2020-02-24 08:37:31,1582533451,"“The First Lady and I have just traveled 8,000...","<p class=""TweetTextSize TweetTextSize--normal ...",[https://twitter.com/pmoindia/status/123184557...,...,False,[],,19616,5070,1012,True,False,,[]

In [33]:
t_df['text']

0      'Party of jobs': Ted Cruz predicts blue-collar...
1      President @realDonaldTrump’s Administration is...
2      At a packed rally in Las Vegas on Friday, Pres...
3      HUGE Latino support in Miami today for @realDo...
4      “The First Lady and I have just traveled 8,000...
                             ...
590    Congressman @MichaelCBurgess has done a Great ...
591    Congressman Brian @Babin4Congress of Texas has...
592    Great photos from a SOUTHERN BORDER WALL Brief...
593     New Gallup Poll  Double-digit improvements in...
594    “Schiff blasted for not focusing on California...
Name: text, Length: 595, dtype: object

In [34]:
t_df.tail()

,screen_name,username,user_id,tweet_id,tweet_url,timestamp,timestamp_epochs,text,text_html,links,...,has_media,img_urls,video_url,likes,retweets,replies,is_replied,is_reply_to,parent_tweet_id,reply_to_users
590,realDonaldTrump,Donald J. Trump,25073877,1222975645447348225,/realDonaldTrump/status/1222975645447348225,2020-01-30 20:11:30,1580415090,Congressman @MichaelCBurgess has done a Great ...,"<p class=""TweetTextSize TweetTextSize--normal ...",[],...,False,[],,39494,9122,1691,True,False,,[]
591,realDonaldTrump,Donald J. Trump,25073877,1222975359722803201,/realDonaldTrump/status/1222975359722803201,2020-01-30 20:10:22,1580415022,Congressman Brian @Babin4Congress of Texas has...,"<p class=""TweetTextSize TweetTextSize--normal ...",[],...,False,[],,34093,8179,1576,True,False,,[]
592,realDonaldTrump,Donald J. Trump,25073877,1222973224092258304,/realDonaldTrump/status/1222973224092258304,2020-01-30 20:01:53,1580414513,Great photos from a SOUTHERN BORDER WALL Brief...,"<p class=""TweetTextSize TweetTextSize--normal ...",[],...,True,[https://pbs.twimg.com/media/EPjfpqFVUAAJ07G.j...,,42479,10661,4613,True,False,,[]
593,IvankaTrump,Ivanka Trump,52544275,1222843974697791488,/IvankaTrump/status/1222843974697791488,2020-01-30 11:28:17,1580383697,New Gallup Poll Double-digit improvements in...,"<p class=""TweetTextSize TweetTextSize--normal ...",[https://thepoliticalinsider.com/gallup-poll-r...,...,False,[],,52530,13374,4201,True,False,,[]
594,realDonaldTrump,Donald J. Trump,25073877,1222907250383245320,/realDonaldTrump/status/1222907250383245320,2020-01-30 15:39:43,1580398783,“Schiff blasted for not focusing on California...,"<p class=""TweetTextSize TweetTextSize--normal ...",[],...,False,[],,123637,28121,24943,True,False,,[]

In [39]:
t_df2 = pd.DataFrame(t.__dict__ for t in trumptweets2)

In [40]:
t_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595 entries, 0 to 594
Data columns (total 21 columns):
screen_name         595 non-null object
username            595 non-null object
user_id             595 non-null object
tweet_id            595 non-null object
tweet_url           595 non-null object
timestamp           595 non-null datetime64[ns]
timestamp_epochs    595 non-null int64
text                595 non-null object
text_html           595 non-null object
links               595 non-null object
hashtags            595 non-null object
has_media           595 non-null bool
img_urls            595 non-null object
video_url           595 non-null object
likes               595 non-null int64
retweets            595 non-null int64
replies             595 non-null int64
is_replied          595 non-null bool
is_reply_to         595 non-null bool
parent_tweet_id     595 non-null object
reply_to_users      595 non-null object
dtypes: bool(3), datetime64[ns](1), int64(4), object(13)
memory usage: 85.5+ KB

In [63]:
trump_df = pd.read_json('trump_tweets')

In [105]:
trump_tweets = pd.concat([trump1, trump2])

In [107]:
trump_tweets.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10629 entries, 0 to 2028
Data columns (total 12 columns):
date         10629 non-null object
username     10629 non-null object
to           909 non-null object
replies      10629 non-null int64
retweets     10629 non-null int64
favorites    10629 non-null int64
text         10270 non-null object
geo          0 non-null float64
mentions     2026 non-null object
hashtags     889 non-null object
id           10629 non-null int64
permalink    10629 non-null object
dtypes: float64(1), int64(4), object(7)
memory usage: 1.1+ MB

In [102]:
trump2 = pd.read_csv('output_got.csv')

In [101]:
trump1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8600 entries, 0 to 8599
Data columns (total 12 columns):
date         8600 non-null object
username     8600 non-null object
to           852 non-null object
replies      8600 non-null int64
retweets     8600 non-null int64
favorites    8600 non-null int64
text         8241 non-null object
geo          0 non-null float64
mentions     1667 non-null object
hashtags     550 non-null object
id           8600 non-null int64
permalink    8600 non-null object
dtypes: float64(1), int64(4), object(7)
memory usage: 806.4+ KB

In [103]:
trump2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2029 entries, 0 to 2028
Data columns (total 12 columns):
date         2029 non-null object
username     2029 non-null object
to           57 non-null object
replies      2029 non-null int64
retweets     2029 non-null int64
favorites    2029 non-null int64
text         2029 non-null object
geo          0 non-null float64
mentions     359 non-null object
hashtags     339 non-null object
id           2029 non-null int64
permalink    2029 non-null object
dtypes: float64(1), int64(4), object(7)
memory usage: 190.3+ KB

In [92]:
trump.columns

Index(['date', 'username', 'to', 'replies', 'retweets', 'favorites', 'text',
       'geo', 'mentions', 'hashtags', 'id', 'permalink'],
      dtype='object')

In [93]:
trump_df.columns

Index(['source', 'text', 'created_at', 'retweet_count', 'favorite_count',
       'is_retweet', 'id_str'],
      dtype='object')

In [95]:
trump.head(3)

,date,username,to,replies,retweets,favorites,text,geo,mentions,hashtags,id,permalink
0,2020-02-23 23:07:43,realDonaldTrump,NaN,10669,22631,120669,"95% Approval Rating in the Republican Party, a...",NaN,NaN,NaN,1231717300627107840,https://twitter.com/realDonaldTrump/status/123...
1,2020-02-23 23:01:44,realDonaldTrump,NaN,3415,15381,65962,NaN,NaN,NaN,NaN,1231715794217623552,https://twitter.com/realDonaldTrump/status/123...
2,2020-02-23 22:51:07,realDonaldTrump,DiamondandSilk,7340,23321,79532,Crazy Bernie and the Democrats should see this...,NaN,NaN,NaN,1231713123180007424,https://twitter.com/realDonaldTrump/status/123...

In [ ]:
['created_at','source', 'text', 'retweet_count', 'favorite_count',
       'is_retweet', 'id_str']
names = ['date', 'username', 'to', 'replies', 'retweets', 'favorites', 'text',
       'geo', 'mentions', 'hashtags', 'id', 'permalink']

In [94]:
trump_df.head(3)

,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str
0,Twitter for iPhone,RT @WhiteHouse: Americans saw plenty of Washin...,2019-12-31 23:35:58+00:00,10643,0,1.0,1212155465599275008
1,Twitter for iPhone,How is the Paris Accord doing? Don’t ask! http...,2019-12-31 23:25:01+00:00,14250,54657,0.0,1212152711753453568
2,Twitter for iPhone,Wonderful account of U.S. Embassy (Iraq) vs. t...,2019-12-31 23:19:49+00:00,13699,45839,0.0,1212151401780064256

In [108]:
collections.insert_many(trump_tweets.to_dict('records'))

In [83]:
justin_t = pd.concat([jt, jt2])

In [140]:
warren2= pd.read_csv('output_got.csv')

In [141]:
warren2.tail()

,date,username,to,replies,retweets,favorites,text,geo,mentions,hashtags,id,permalink
1188,2011-09-14 16:08:37,ewarren,NaN,3,6,0,Thanks to all who said hello this AM at the Br...,NaN,NaN,#elizabethwarren,114007653193236481,https://twitter.com/ewarren/status/11400765319...
1189,2011-09-14 12:00:38,ewarren,NaN,4,5,1,Meeting South Boston commuters at the Broadway...,NaN,NaN,#elizabethwarren,113945247830130689,https://twitter.com/ewarren/status/11394524783...
1190,2011-09-14 10:31:41,ewarren,NaN,7,195,30,I'm running to represent the people of MA in t...,NaN,NaN,#elizabethwarren,113922862552850433,https://twitter.com/ewarren/status/11392286255...
1191,2011-09-08 18:41:51,ewarren,NaN,1,57,4,Sign my petition: Tell the Senate GOP to stop ...,NaN,NaN,NaN,111871889852465152,https://twitter.com/ewarren/status/11187188985...
1192,2011-08-19 18:52:55,ewarren,NaN,4,43,3,Launched exploratory committee for Senate. Loo...,NaN,NaN,NaN,104626914974629888,https://twitter.com/ewarren/status/10462691497...

In [118]:
 = pd.concat([bernie1, bernie2, bernie3, bernie4])

In [119]:
bernie_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12693 entries, 0 to 55
Data columns (total 12 columns):
date         12693 non-null object
username     12693 non-null object
to           1308 non-null object
replies      12693 non-null int64
retweets     12693 non-null int64
favorites    12693 non-null int64
text         12686 non-null object
geo          0 non-null float64
mentions     1732 non-null object
hashtags     2780 non-null object
id           12693 non-null int64
permalink    12693 non-null object
dtypes: float64(1), int64(4), object(7)
memory usage: 1.3+ MB

In [124]:
pete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7378 entries, 0 to 7377
Data columns (total 12 columns):
date         7378 non-null object
username     7378 non-null object
to           2016 non-null object
replies      7378 non-null int64
retweets     7378 non-null int64
favorites    7378 non-null int64
text         7355 non-null object
geo          0 non-null float64
mentions     2358 non-null object
hashtags     1335 non-null object
id           7378 non-null int64
permalink    7378 non-null object
dtypes: float64(1), int64(4), object(7)
memory usage: 691.8+ KB

In [126]:
joe_df = pd.concat([joe,joe2])

In [129]:
joe_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3551 entries, 0 to 1
Data columns (total 12 columns):
date         3551 non-null object
username     3551 non-null object
to           340 non-null object
replies      3551 non-null int64
retweets     3551 non-null int64
favorites    3551 non-null int64
text         3548 non-null object
geo          0 non-null float64
mentions     549 non-null object
hashtags     646 non-null object
id           3551 non-null int64
permalink    3551 non-null object
dtypes: float64(1), int64(4), object(7)
memory usage: 360.6+ KB

In [142]:
warren_df = pd.concat([warren, warren2])

In [143]:
warren_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7993 entries, 0 to 1192
Data columns (total 12 columns):
date         7993 non-null object
username     7993 non-null object
to           1306 non-null object
replies      7993 non-null int64
retweets     7993 non-null int64
favorites    7993 non-null int64
text         7992 non-null object
geo          0 non-null float64
mentions     2065 non-null object
hashtags     2841 non-null object
id           7993 non-null int64
permalink    7993 non-null object
dtypes: float64(1), int64(4), object(7)
memory usage: 811.8+ KB

In [134]:
amy_df = pd.concat([amy, amy2])

In [135]:
amy_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10251 entries, 0 to 7550
Data columns (total 12 columns):
date         10251 non-null object
username     10251 non-null object
to           1150 non-null object
replies      10251 non-null int64
retweets     10251 non-null int64
favorites    10251 non-null int64
text         10246 non-null object
geo          0 non-null float64
mentions     4138 non-null object
hashtags     1957 non-null object
id           10251 non-null int64
permalink    10251 non-null object
dtypes: float64(1), int64(4), object(7)
memory usage: 1.0+ MB

In [136]:
bern_collections = db.bernie_tweets
joe_collections = db.joe_tweets
pete_collections = db.pete_tweets
amy_collections = db.amy_tweets
warren_collections = db.warren_tweets

In [144]:
bern_collections.insert_many(bernie_df.to_dict('records'))
joe_collections.insert_many(joe_df.to_dict('records'))
pete_collections.insert_many(pete.to_dict('records'))
amy_collections.insert_many(amy_df.to_dict('records'))
warren_collections.insert_many(warren_df.to_dict('records'))